// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  firstName: __t.string(),
  lastName: __t.string(),
  company: __t.string(),
  title: __t.string(),
  bio: __t.string(),
  categoryKey: __t.string(),
  categories: __t.array(__t.string()),
  email: __t.option(__t.string()),
  phone: __t.option(__t.string()),
  city: __t.string(),
  state: __t.string(),
  zip: __t.string(),
  country: __t.string(),
  website: __t.string(),
  profileImage: __t.string(),
  dataJson: __t.string(),
};
