// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  firstName: __t.string().name("first_name"),
  lastName: __t.string().name("last_name"),
  company: __t.string(),
  title: __t.string(),
  bio: __t.string(),
  categoryKey: __t.string().name("category_key"),
  categories: __t.array(__t.string()),
  email: __t.string(),
  phone: __t.string(),
  city: __t.string(),
  state: __t.string(),
  zip: __t.string(),
  country: __t.string(),
  website: __t.string(),
  profileImage: __t.string().name("profile_image"),
  dataJson: __t.string().name("data_json"),
  created: __t.timestamp(),
  updated: __t.timestamp(),
});
