// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import ClearDirectoryPeopleReducer from "../clear_directory_people_reducer";
import CreateDirectoryCategoryReducer from "../create_directory_category_reducer";
import CreateDirectoryPersonReducer from "../create_directory_person_reducer";
import CreateDirectoryPlaceReducer from "../create_directory_place_reducer";
import DeleteDirectoryPersonReducer from "../delete_directory_person_reducer";
import SayHelloReducer from "../say_hello_reducer";
import UpdateDirectoryPersonReducer from "../update_directory_person_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type ClearDirectoryPeopleParams = __Infer<typeof ClearDirectoryPeopleReducer>;
export type CreateDirectoryCategoryParams = __Infer<typeof CreateDirectoryCategoryReducer>;
export type CreateDirectoryPersonParams = __Infer<typeof CreateDirectoryPersonReducer>;
export type CreateDirectoryPlaceParams = __Infer<typeof CreateDirectoryPlaceReducer>;
export type DeleteDirectoryPersonParams = __Infer<typeof DeleteDirectoryPersonReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;
export type UpdateDirectoryPersonParams = __Infer<typeof UpdateDirectoryPersonReducer>;

