/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsNotesRouteImport } from './routes/apps/notes'
import { Route as Apps3dEngineRouteImport } from './routes/apps/3d-engine'

const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNotesRoute = AppsNotesRouteImport.update({
  id: '/apps/notes',
  path: '/apps/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const Apps3dEngineRoute = Apps3dEngineRouteImport.update({
  id: '/apps/3d-engine',
  path: '/apps/3d-engine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/directory': typeof DirectoryRoute
  '/space': typeof SpaceRoute
  '/apps/3d-engine': typeof Apps3dEngineRoute
  '/apps/notes': typeof AppsNotesRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/directory': typeof DirectoryRoute
  '/space': typeof SpaceRoute
  '/apps/3d-engine': typeof Apps3dEngineRoute
  '/apps/notes': typeof AppsNotesRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/directory': typeof DirectoryRoute
  '/space': typeof SpaceRoute
  '/apps/3d-engine': typeof Apps3dEngineRoute
  '/apps/notes': typeof AppsNotesRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/directory'
    | '/space'
    | '/apps/3d-engine'
    | '/apps/notes'
    | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/directory'
    | '/space'
    | '/apps/3d-engine'
    | '/apps/notes'
    | '/apps'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/directory'
    | '/space'
    | '/apps/3d-engine'
    | '/apps/notes'
    | '/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DirectoryRoute: typeof DirectoryRoute
  SpaceRoute: typeof SpaceRoute
  Apps3dEngineRoute: typeof Apps3dEngineRoute
  AppsNotesRoute: typeof AppsNotesRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/notes': {
      id: '/apps/notes'
      path: '/apps/notes'
      fullPath: '/apps/notes'
      preLoaderRoute: typeof AppsNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/3d-engine': {
      id: '/apps/3d-engine'
      path: '/apps/3d-engine'
      fullPath: '/apps/3d-engine'
      preLoaderRoute: typeof Apps3dEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DirectoryRoute: DirectoryRoute,
  SpaceRoute: SpaceRoute,
  Apps3dEngineRoute: Apps3dEngineRoute,
  AppsNotesRoute: AppsNotesRoute,
  AppsIndexRoute: AppsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
